spring:
  application:
    name: NoSQL2SQL
  datasource:
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:password}
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
#  cloud:
#    aws:
#      region:
#        static: "us-east-1"
#      credentials:
#        access-key: "test"
#        secret-key: "test"
#      s3:
#        endpoint: "http://s3.localhost.localstack.cloud:4566"
#      dynamodb:
#        endpoint: "http://localhost:4566"

runtime:
  # mode may either be "cli" or "service"
  mode: service

logging:
  level:
    root: info
    com.guidewire: debug

mapping:
  s3:
    bucket-name: ${EXPORT_BUCKET_NAME}
    prefix:
  dynamodb:
    dynamo-table-name: ${DYNAMO_TABLE_NAME}
    discriminator-attribute-name: recordType
    partition-key-name: pk
    sort-key-name: sk
  postgresql:
    recreate-tables: true
server:
  port: 8085
springdoc:
  swagger-ui:
    path: /swagger-ui.html